services:
  postgres_db:
    container_name: postgres_db_prod
    image: postgres:17.4-alpine
    volumes:
      - db_data_prod:/var/lib/postgresql/data
      - shared_data_prod:/var/shared
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=blackbook_production
    networks:
      - blackbook_network_prod
    ports:
      - 5435:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  blackbook:
    container_name: blackbook_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=blackbook_production
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=test_pass
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - shared_data_prod:/var/shared
      - gem_cache_prod:/usr/local/bundle/gems
      - ./storage:/app/storage
    networks:
      - blackbook_network_prod
    ports:
      - 3002:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  blackbook_network_prod:

volumes:
  db_data_prod:
  gem_cache_prod:
  shared_data_prod:
